### ISSUE TITLE
could you tell me about the performance?

### ISSUE THREAD

**Issue by wangjianpeng** [DaVikingCode/UnityRuntimeSpriteSheetsGenerator#1]
I want to create large texture atlas at runtime on mobile  ,but i don't have a better profiler to find which stage will affect performance during generate atlas on the fly.
As i know , large atlas will overhead more video memory ,and decrease draw call in unity.If i use unity builtin atlas packer ,it will reimport for different platform setting, and decrease load  and encode texture time at runtime , the cons is i must put all texture in the unity editor.
if i want to download more textures from server, and  generate large  atlas with there textures,  which stage it will overhead cost during create large atlas , file I/O read write, ram memory ,garbage collect , cpu time cost or gpu video memory.
could you tell me some  compare result about runtime atlas create  and builtin atlas packer ?
sorry for my bad english, i am just interested in what runtime atlas create do and can't find more useful repository by .net except this one.

**Comment by alamboley** [comment]
Hello,

If you can already create your Atlas in Unity, there is no better way than using Unity's Sprite Atlas feature.

Otherwise if you must generate them at runtime, don't forget a texture shouldn't exceed 4096 x 4096 (note some old mobile are stuck with 2048x2048).

Sprite Atlas built-in with Unity are very efficient, if your problem is application size you should have a look on Unity's AssetBundles. Runtime Atlas is only if you have no other choice!
